# Generated by Django 6.0.2 on 2026-02-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslide',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='heroslide',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
