# Generated by Django 6.0.2 on 2026-03-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
