# Generated by Django 6.0.2 on 2026-03-02 06:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contactmessage_admin_reply_contactmessage_is_replied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_replied',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='replied_at',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Replied', 'Replied')], default='Open', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='ticket_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
