# Generated by Django 6.0.2 on 2026-03-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_order_courier_name_order_estimated_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='current_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Order Placed', max_length=50),
        ),
    ]
