# Generated by Django 6.0.2 on 2026-03-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_orderitem_current_location_orderitem_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
